media:
  - name: images
    label: Images
    input: content/images
    output: /images
    path: content/images
    extensions: [jpg, jpeg, png, webp, svg, gif]  

content:
  - name: contentItem
    filename: "{fields.title}.md"
    label: Item
    type: collection
    path: content
    fields:
      - name: title
        label: Title
        type: string
        options:
          minlength: 3
          required: true
      - name: imageSrc
        label: Afbeelding
        type: image
        options:
          media: images                
          required: true
